name: Create and publish a Docker image

on:
  workflow_call:
    outputs:
      image:
        description: 'The image that was built'
        value: ${{ jobs.build-and-push-image.outputs.image }}

    inputs:
      runs-on:
        description: 'The type of machine to run the job on'
        required: false
        type: string
        default: ubuntu-latest
      registry:
        description: 'The registry to push the image to'
        required: false
        type: string
        default: registry.hub.docker.com
      image:
        description: 'The name of the image'
        required: true
        type: string
      prefix:
        description: 'prefix of the image tag'
        required: true
        type: string

    secrets:
      DOCKER_USERNAME:
        description: 'Username for the registry'
        required: true
      DOCKER_PASSWORD:
        description: 'Password for the registry'
        required: true

jobs:
  build-and-push-image:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.registry }}/${{ inputs.image }}
          tags: |
            type=sha,prefix=${{ inputs.prefix }}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    outputs:
      image: ${{ steps.meta.outputs.tags }}
