on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The type of machine to run the job on'
        required: false
        type: string
        default: ubuntu-latest
      repository:
        description: 'The repository to checkout'
        required: true
        type: string
      path:
        required: true
        type: string
      selector:
        required: true
        type: string
      value:
        required: true
        type: string
      is_plain_text:
        required: false
        type: boolean
        default: false

    secrets:
      REPO_PAT:
        description: 'Personal access token for the repository'
        required: true

jobs:
  deploy:
    name: GitOps
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Install dasel
        run: |
          curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
          mv ./dasel /usr/local/bin/dasel

      - name: Checkout deploy repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: main
          token: ${{ secrets.REPO_PAT }}

      - name: Update Version
        if: ${{ !inputs.is_plain_text }}
        run: |
          dasel put \
          -f ${{ inputs.path }} \
          -o ${{ inputs.path }} \
          -t string \
          -v ${{ inputs.value }} \
          ${{ inputs.selector }}

      - name: Update Version(plain text)
        if: ${{ inputs.is_plain_text }}
        run: |
          sed \
          -i \
          's/${{ inputs.selector }}/${{ inputs.value }}/g' \
          ${{ inputs.path }}

      - name: Check diff
        id: check-diff
        run: |
          echo "has_diff=$(git diff --name-only)" >> $GITHUB_OUTPUT

      - name: Commit
        if: ${{ steps.check-diff.outputs.has_diff != '' }}
        run: |
          git config --local user.email "karta09104@gmail.com"
          git config --local user.name "Leo Lin"
          git add ${{ inputs.path }}
          git commit \
              --message "feat: update ${{ inputs.path }}-${{ inputs.selector }}"
          git push origin main
          echo "**New commit**" >> $GITHUB_STEP_SUMMARY
          echo "[${{ inputs.repository }}@$(git rev-parse HEAD)](https://github.com/${{ inputs.repository }}/commit/$(git rev-parse HEAD))" >> $GITHUB_STEP_SUMMARY
