name: Lint

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: ${{ inputs.image }}
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run flake8
        run: flake8 .

      - name: Run isort
        run: isort . --check

      - name: Run black
        run: black . --check