on:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/build-image.yaml
      - Dockerfile

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Setup image version
        id: image-version
        run: |
          sha=${{ github.sha }}
          echo "version=${{ steps.branch-name.outputs.current_branch }}-${sha:0:7}" >> $GITHUB_OUTPUT
    outputs:
      branch: ${{ steps.branch-name.outputs.current_branch }}
      tag: ${{ steps.image-version.outputs.version }}

  build-image:
    permissions:
      contents: read
      packages: write
    needs:
      - setup
    uses: ./.github/workflows/build-image.yaml
    with:
      image: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}
      tags: ${{ needs.setup.outputs.tag }},${{ needs.setup.outputs.branch }}-latest
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
